### ISSUE TITLE
Python 10 Compatibility

### ISSUE THREAD

**Issue by ksnyderSP** [vangheem/pyzipcode#16]
When trying to run this package with Python 10 I'm shown the error:
AttributeError: module 'collections' has no attribute 'MutableMapping'

https://github.com/pymedusa/Medusa/issues/10253

**Comment by vangheem** [comment]
Is this a problem or not? I can look into fixing it next week.

**Comment by ksnyderSP** [comment]
Nope, user error on my part. Sorry about that!
